<h1 align='center'>Two Dimensional Array</h1>

### Creating a 2D array

In [4]:
import numpy as np

In [5]:
twoDArray = np.array([[11, 15, 16], [19, 14, 77], [12, 13, 8]])

### Insert in 2D Array

In twoDArray insert at index 3, [[1, 2, 3]] 0 and 1 represents axis 0 for horizontally 1 for vertically

In [11]:
twoDArray = np.insert(twoDArray, 3, [[1, 2, 3]], 0)

### Length of 2D array

In [13]:
len(twoDArray)

4

### Length of 2D array at an index

In [14]:
len(twoDArray[1])

3

### Access the element of a 2D array at index row, col

In [40]:
def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('Incorrect Index')
    else:
        print(array[rowIndex][colIndex])

In [41]:
accessElements(twoDArray, 1, 2)

77


### Traverse through a 2D array

In [43]:
def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

In [44]:
traverseTDArray(twoDArray)

11
15
16
19
14
77
12
13
8
1
2
3


### Search through a 2D array

In [54]:
print(twoDArray)

[[11 15 16]
 [19 14 77]
 [12 13  8]
 [ 1  2  3]]


In [47]:
def twoDsearch(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located index '+str(i)+" "+str(j)

    return 'The element no found'

In [49]:
print(twoDsearch(twoDsearch, 1))

The value is located index 3 0


### Delete from a 2D array

In [52]:
newTDArray = np.delete(twoDArray, 1, axis=1)

In [53]:
print(newTDArray)

[[11 16]
 [19 77]
 [12  8]
 [ 1  3]]
